### ISSUE TITLE
":" and "_" are valid first characters of a nodeName

### ISSUE THREAD

**Issue by dturing** [vflash/easysax#5]
The XML specification defines:

`NameStartChar	   ::=   	":" | [A-Z] | "_" | [a-z] | [#xC0-#xD6] | [#xD8-#xF6] | [#xF8-#x2FF] | [#x370-#x37D] | [#x37F-#x1FFF] | [#x200C-#x200D] | [#x2070-#x218F] | [#x2C00-#x2FEF] | [#x3001-#xD7FF] | [#xF900-#xFDCF] | [#xFDF0-#xFFFD] | [#x10000-#xEFFFF]
`

But easysax only accepts [A-Za-z]: [see here](https://github.com/vflash/easysax/blob/master/easysax.js#L570), else it throws "first char nodeName".

Personally, i don't care to much about those higher unicode codepoints from the spec (and that would touch some other areas inside easysax i think), but i have some data on my hands where some tags start with underscore.

Could at least ":" and "_" be added to the list of valid first chars for nodeName?

**Comment by vflash** [comment]
"_" - поправлю
":" - приведите xml пример

**Comment by dturing** [comment]
My russian is really bad, but google translate tells me you want justification for the ":". 

While i don't personally much care for XML nodes like <:foo/>, it seems to be a valid (first) character for XML node names. It looks weird (like an empty namespace), but [the spec is quite clear](https://www.w3.org/TR/2008/REC-xml-20081126/#NT-NameStartChar). The scala guys also [stumbled](https://github.com/scala/scala-xml/issues/94) [upon this](https://github.com/scala/scala-xml/pull/93/commits/ee91a55f94a53739dee17b9c204f278ae81090db)

**Comment by vflash** [comment]
fix v0.2.0
