### ISSUE TITLE
Various improvements

### ISSUE THREAD

**Issue by nikku** [vflash/easysax#6]
First of all dobroi djen and thanks for this awesome, blazing fast XML parser @vflash.

I've forked your library as [nikku/easysax](https://github.com/nikku/easysax) and plan to use it in production. In the course of trying it out, I've carried out [various changes](https://github.com/vflash/easysax/compare/master...nikku:master). A few of these are improvements you could consider to merge:

* CHORE: rewrite test suite to use deep equals (https://github.com/nikku/easysax/commit/6b5d82981f5722ec15508cab435574e9d3a02a1e), this provides proper diffs between expected and actual data
* FIX: handle nested namespaces correctly (https://github.com/nikku/easysax/commit/60daae307722413414d9ecdca94bd8c8a325ce21)
* FEAT: provide parse context with `{ line, column, data }` to use upon user request (https://github.com/nikku/easysax/commit/1733b5789f19bb08cf26c216666034f976d78155), this is helpful for library users to retrieve the context on parser or XML processing errors

Keep up the good work and have a nice day!

Nico

**Comment by vflash** [comment]
Добрый день. Изменения как есть принять не могу. 
Идеи хорошие.  Доработаю ошибки и namespaces к следующей версии.

**Comment by nikku** [comment]
You're welcome to pull in the changes you want. Have a great afternoon.
